feat: add a program file

diff --git a/quick-backup-cli b/quick-backup-cli
--- a/quick-backup-cli
+++ b/quick-backup-cli
@@ -4,14 +4,24 @@ PROGRAM_NAME="quick-backup-cli"
 VERSION="v1.6"
 
 CONFIG_DEST="$1"
-
 CONFIG=$HOME/.config/
-LOCAL_SHARE=$HOME/.local/share/
+PROGRAMS_CSV="$CONFIG""$PROGRAM_NAME"/programs.csv
 
-RETROARCH_DIR_NAME="retroarch"
-YUZU_DIR_NAME="yuzu"
-RPCS3_DIR_NAME="rpcs3"
-OSU_LAZER_DIR_NAME="osu"
+# $1 directory
+check_trailing_slash() {
+	if ! echo "$1" | grep -q '\b/$'; then
+		printf "Error: Directory must end with a trailing '/'.\n"
+		exit 1
+	fi
+}
+
+# $1 directory
+check_dir_exists() {
+	if [ ! -d "$1" ]; then
+		printf "Error: The directory '%s' does not exist.\n" "$1"
+		exit 1
+	fi
+}
 
 version_info() {
 	printf "%s %s\n" $PROGRAM_NAME $VERSION
@@ -42,17 +52,9 @@ if [ ! -d "$1" ]; then
 	printf "Usage: %s [DIRECTORY]\n" $PROGRAM_NAME
 	printf "Try '%s --help' for more information.\n" $PROGRAM_NAME
 	exit 1
-elif ! echo "$1" | grep -q '\b/$'; then
-	printf "Error: Directory must end with a trailing '/'.\n"
-	exit 1
+else
+	check_trailing_slash "$1"
 fi
-
-check_dir_exists() {
-	if [ ! -d "$1" ]; then
-		printf "Error: The directory '%s' does not exist.\n" "$1"
-		exit 1
-	fi
-}
 
 trash_and_copy() {
 	# If directory $2 and $3 do not exist, then check_dir_exists will
@@ -80,52 +82,73 @@ get_confirmation() {
 	fi
 }
 
-backup_or_download() {
+print_programs() {
+	printf "Select a program (number):\n"
+	num=1
+	while IFS="," read -r program_name _; do
+		echo "$num. $program_name"
+		num=$((num + 1))
+	done <"$PROGRAMS_CSV"
+}
+
+configure() {
+	printf "Enter program directory name (e.g. yuzu/):\n"
+	read -r program_name
+	printf "Enter program config directory (e.g. /home/user/.config/):\n"
+	read -r program_directory
+
+	# TODO: check for preceding and trailing slash as the path must be absolute
+	check_trailing_slash "$program_name"
+	check_trailing_slash "$program_directory"
+	check_dir_exists "$program_directory"
+	check_dir_exists "$program_directory$program_name"
+
+	mkdir -p "$CONFIG""$PROGRAM_NAME"
+	echo "$program_name,$program_directory" >>"$PROGRAMS_CSV"
+}
+
+backup() {
+	print_programs
+	read -r program_num
+	program_name=$(sed -n "$program_num"p "$PROGRAMS_CSV" | cut -f1 -d",")
+	program_directory=$(sed -n "$program_num"p "$PROGRAMS_CSV" | cut -f2 -d",")
+	# TODO: check if line num exists
+
+	get_confirmation "$CONFIG_DEST$program_name" "$program_directory$program_name" "$CONFIG_DEST"
+	printf "Backing up...\n"
+	trash_and_copy "$CONFIG_DEST$program_name" "$program_directory$program_name" "$CONFIG_DEST"
+	printf "Done!\n"
+}
+
+download() {
+	print_programs
+	read -r program_num
+	program_name=$(sed -n "$program_num"p "$PROGRAMS_CSV" | cut -f1 -d",")
+	program_directory=$(sed -n "$program_num"p "$PROGRAMS_CSV" | cut -f2 -d",")
+	# TODO: check if line num exists
+
+	get_confirmation "$program_directory$program_name" "$CONFIG_DEST$program_name" "$program_directory"
+	printf "Downloading...\n"
+	trash_and_copy "$program_directory$program_name" "$CONFIG_DEST$program_name" "$program_name"
+	printf "Done!\n"
+}
+
+select_an_option() {
 	printf "Select an option (number):\n"
-	printf "1. Backup\n"
-	printf "2. Download\n"
+	printf "1. Configure\n"
+	printf "2. Backup\n"
+	printf "3. Download\n"
 	read -r option
 
 	if [ "$option" = "1" ]; then
-		get_confirmation "$CONFIG_DEST$1" "$2" "$CONFIG_DEST"
-
-		printf "Backing up...\n"
-		trash_and_copy "$CONFIG_DEST$1" "$2" "$CONFIG_DEST"
-		printf "Done!\n"
+		configure
 	elif [ "$option" = "2" ]; then
-		get_confirmation "$2" "$CONFIG_DEST$1" "$3"
-
-		printf "Downloading...\n"
-		trash_and_copy "$2" "$CONFIG_DEST$1" "$3"
-		printf "Done!\n"
+		backup
+	elif [ "$option" = "3" ]; then
+		download
 	else
 		printf "Error: Invalid option.\n"
 	fi
 }
 
-backup_or_download_to_config() {
-	backup_or_download "$1" "$CONFIG$1" "$CONFIG"
-}
-
-backup_or_download_to_local() {
-	backup_or_download "$1" "$LOCAL_SHARE$1" "$LOCAL_SHARE"
-}
-
-printf "Select a program (number):\n"
-printf "1. Retroarch\n"
-printf "2. Yuzu\n"
-printf "3. RPCS3\n"
-printf "4. osu!lazer\n"
-read -r program
-
-if [ "$program" = "1" ]; then
-	backup_or_download_to_config "$RETROARCH_DIR_NAME"
-elif [ "$program" = "2" ]; then
-	backup_or_download_to_local "$YUZU_DIR_NAME"
-elif [ "$program" = "3" ]; then
-	backup_or_download_to_config "$RPCS3_DIR_NAME"
-elif [ "$program" = "4" ]; then
-	backup_or_download_to_local "$OSU_LAZER_DIR_NAME"
-else
-	printf "Error: Invalid program.\n"
-fi
+select_an_option
